/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binus.datastructure.algorithmvisualizer;

import java.util.ArrayList;
import org.javatuples.Pair;
import binus.datastructure.algorithmvisualizer.algorithms.BubbleSort;

public class App {
    public String getGreeting() {
        DoublyLinkedList list = new DoublyLinkedList();

        ArrayList<Integer> currentState = new ArrayList<Integer>();
        currentState.add(3);
        currentState.add(2);
        currentState.add(4);
        currentState.add(1);
        Pair<Integer, Integer> comparedElements = new Pair<Integer, Integer>(-1, -1);

        SortingContainer currentStep = new SortingContainer(currentState, currentState, comparedElements, 0, false, false, false);
        list.addNode(currentStep);
        
        while (!currentStep.getIsFinished()) {
            currentStep = BubbleSort.step(currentStep);
            list.addNode(currentStep);
        }

        list.display();

        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
