/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binus.datastructure.algorithmvisualizer;

import binus.datastructure.algorithmvisualizer.views.AlgorithmVisualizer;

public class App {
    public void launchApplication(String[] args) {
        // Launch the JavaFX application
        AlgorithmVisualizer.main(args);
    }

    public static void main(String[] args) {
        new App().launchApplication(args);
    }
}
